# Generated by Django 3.0.5 on 2020-05-04 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('pages', models.IntegerField(default=0)),
                ('native_language', models.CharField(max_length=3)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinoxenic.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('zh', models.CharField(max_length=200)),
                ('en', models.CharField(max_length=200)),
                ('zh_trans', models.CharField(max_length=200)),
                ('page', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinoxenic.Book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinoxenic.Category')),
            ],
        ),
    ]
